### model
model_name_or_path: /data/sjtu/wrx/model_weights/Llama3-8B-Chinese-Chat/

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 256

### dataset
dataset: identity_anding,psychgpt_sft
template: llama3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/sjtu/wrx/llamafactory/psychgpt_sft-llama3-8b-lora-256-0802
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 1000
