### model
model_name_or_path: /data/sjtu/wrx/model_weights/Qwen2-7B/

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 256

### dataset
dataset: identity_psychgpt,psychgpt_cpt
template: qwen
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/sjtu/wrx/llamafactory/psychgpt_cpt-qwen2-7b-lora-256-0117
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 3000
