### model
model_name_or_path: /data/sjtu/wrx/llamafactory/psychgpt-r1-0313-refine-sft-dpo-task2-knowledge-merge/

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 256

### dataset
dataset: identity_psychgpt,psychgpt_sft_refine
template: qwen
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/sjtu/wrx/llamafactory/psychgpt-r1-0313-refine-sft-dpo-task2-knowledge-sft-CMBCME
logging_steps: 10
save_steps: 3000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4 
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 1000
